### ISSUE TITLE
SOLID_Open/Close Principle 

### ISSUE THREAD

**Issue by Urunov** [Urunov/Interview-Preparation-WAY#5]
Open/Close Principle

**Comment by rom0noff** [comment]
In object-oriented programming, the open–closed principle (OCP) states "software entities (classes, modules, functions, etc.) should be open for extension, but closed for modification"; that is, such an entity can allow its behaviour to be extended without modifying its [source code](https://en.wikipedia.org/wiki/Source_Code_Control_System).
The name open–closed principle has been used in two ways. Both ways use generalizations (for instance, inheritance or delegate functions) to resolve the apparent dilemma, but the goals, techniques, and results are different.
Open–closed principle is one of the five SOLID principles of object-oriented design.

**Comment by rom0noff** [comment]
The purpose of those principles is to allow developers to write better software. 
The software is easier and cheaper to maintain, easier to understand, faster to develop in a team, and easier to test. 
Following those principles doesn’t guarantee success, but avoiding them will lead in most cases to at least sub-optimal results in terms of functionality, cost, or both.
It's now time for the O in SOLID, known as the open-closed principle. Simply put, classes should be open for extension but closed for modification.
In doing so, we stop ourselves from modifying existing code and causing potential new bugs in an otherwise happy application.

**Comment by rom0noff** [comment]
Open for extension – This means that the module’s behavior can be extended. As the requirements of the application change, we can extend the module with new behaviors that satisfy those changes. In other words, we are able to change what the module does.
Closed for modification – Extending the behavior of a module does not result in changes to the source or binary code of the module. The binary executable version of the module, whether in a linkable library, a DLL, or a Java .jar, remains untouched. Abstractions shouldn’t depend on details. Details should depend on abstractions.


![Image](https://github.com/Urunov/Interview-Preparation-WAY/assets/99829336/911077af-a65f-4cef-b2ab-4fb3a0609680)

**Comment by rom0noff** [comment]
Why Should You Apply the Open/Closed Principle?
Software systems that are not carefully designed, tend to develop an increasing amount of unwanted interdependencies. 
Often these interdependencies are accidental, and they accumulate to such an extent that it becomes increasingly hard to keep track of them. 
Changes in one part of such a codebase often necessitate changes somewhere else. These changes, in turn, require modifications in another part of the system leading to a domino effect. 
If you have to change the code in various parts of the codebase to fulfill a new requirement, your system will become unstable and increasingly behave in a non-deterministic manner.
